### PR TITLE
Purchase multiple wares in one go

### PR DESCRIPTION
**Pull request by jonasKjellerup**
The feature makes it possible to purchase multiple wares in one go. E.g.:
```
sts -u username øl+monster+panta:2
```
(Results in purchase of one monster and beer + 2x pant a)

Notes:
- If the count is not specified for a ware it will default to the value given by the `-c` flag or `1` (in that order)  
  e.g.: `sts -u username -c 2 monster+panta` will purchase 2x monster and panta
- If a unknown shorthand is used the entire purchase will be canceled (not just that of the unknown item)

### CODE REVIEW

**Comment by Zaph-x** [comment]
Hvordan håndteres eksempelvis `sts -i monster+øl -c 2` som køber både monster og øl, med count sat til 2?

**Review by falkecarlsen — APPROVED** [review]
LGTM - fix lige merge conflicts pls

**Comment by jonasKjellerup** [comment]
Merge conflict has been fixed

**Comment by falkecarlsen** [comment]
I think we should look into fixing the parser to just allow as stregsystemet does normally, e.g:
> tester 1:2 2:2

No reason to add a client-specific delimiter imo. Sorry for making you fix conflicts @jonasKjellerup :)

**Pull request closed without merging**
